kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: api
  image: plugins/docker
  settings:
    target: api
    repo: rkojedzinszky/thermo-center-api
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true

- name: app
  image: plugins/docker
  settings:
    target: app
    repo: rkojedzinszky/thermo-center-app
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true
    cache_from:
    - rkojedzinszky/thermo-center-api

- name: ui
  image: plugins/docker
  settings:
    target: ui
    repo: rkojedzinszky/thermo-center-ui
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true
    cache_from:
    - rkojedzinszky/thermo-center-api
    - rkojedzinszky/thermo-center-app

- name: receiver
  image: plugins/docker
  settings:
    dockerfile: receiver/Dockerfile
    repo: rkojedzinszky/thermo-center-receiver
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true

- name: ws
  image: plugins/docker
  settings:
    dockerfile: ws/Dockerfile
    repo: rkojedzinszky/thermo-center-ws
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true
