kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: rkojedzinszky/thermo-center
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
