kind: pipeline
name: build

platform:
  os: linux

steps:
- name: versions
  image: alpine
  commands:
  - apk --no-cache add git
  - git fetch --tags
  - V=$(git describe --tags HEAD)
  - 'echo "export default \\"$V\\";" > www/version.js'
  - 'sed -i -e "/^const cacheVersion/s/ =.*/ = \\"$V\\";/" www/sw.js'

- name: api
  image: plugins/docker
  settings:
    target: api
    repo: rkojedzinszky/thermo-center-api
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true
  depends_on:
  - versions
  volumes:
  - name: docker
    path: /var/lib/docker

- name: receiver
  image: plugins/docker
  settings:
    dockerfile: receiver/Dockerfile
    repo: rkojedzinszky/thermo-center-receiver
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true

- name: golang-build
  image: golang:1.15-alpine
  commands:
  - apk --no-cache add binutils
  - mkdir -p ${GOPATH}/src/github.com/rkojedzinszky
  - ln -sf $(pwd) ${GOPATH}/src/github.com/rkojedzinszky/thermo-center
  - cd ${GOPATH}/src/github.com/rkojedzinszky/thermo-center
  - mkdir bin
  - CGO_ENABLED=0 go build -o bin/grpcserver ./cmd/grpcserver
  - CGO_ENABLED=0 go build -o bin/ws ./ws
  - strip -s bin/*

- name: grpcserver
  image: plugins/docker
  settings:
    dockerfile: Dockerfile.grpcserver
    repo: rkojedzinszky/thermo-center-grpcserver
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true
  depends_on:
  - golang-build

- name: ws
  image: plugins/docker
  settings:
    dockerfile: Dockerfile.ws
    repo: rkojedzinszky/thermo-center-ws
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true
  depends_on:
  - golang-build

- name: ui
  image: plugins/docker
  settings:
    target: ui
    repo: rkojedzinszky/thermo-center-ui
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true
  depends_on:
  - api
  volumes:
  - name: docker
    path: /var/lib/docker

volumes:
- name: docker
  temp: {}
