version: '3'

services:
  memcached:
    image: memcached:alpine
    command: memcached -m 8
    user: "11211"
  mqtt:
    image: eclipse-mosquitto:1.5
  receiver:
    image: rkojedzinszky/thermo-center-receiver
    volumes:
    - "/sys/class/gpio/gpio200:/gpio"
    devices:
    - "/dev/spidev0.0:/dev/spidev0.0"
  grpcserver:
    image: rkojedzinszky/thermo-center-grpcserver
    environment:
      DBNAME: ${DBNAME}
      DBHOST: ${DBHOST}
      DBPORT: ${DBPORT}
      DBUSER: ${DBUSER}
      DBPASSWORD: ${DBPASSWORD}
  api:
    image: rkojedzinszky/thermo-center-api
    ports:
    - "8080:8080"
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DBNAME: ${DBNAME}
      DBHOST: ${DBHOST}
      DBPORT: ${DBPORT}
      DBUSER: ${DBUSER}
      DBPASSWORD: ${DBPASSWORD}
      DBCONNMAXAGE: ""
  ws:
    image: rkojedzinszky/thermo-center-ws
    ports:
    - "8081:8081"
    environment:
      THERMO_CENTER_API_HOST: api
  ui:
    image: rkojedzinszky/thermo-center-ui
    ports:
    - "8082:8080"

